### ISSUE TITLE
Reproduce the ternary plot in Figure 1A

### ISSUE THREAD

**Issue by zhanglab2008** [almutlue/batch_snakemake#1]
Hi team,
Great work! I like the figure 1a in your paper to show the percent of variance explained by batch or cell type for each gene. Would you mind sending me your codes to reproduce the figure? You can send it to my email if that's OK: ptec8888@gmail.com
Many thanks!
Wish you every success in your research.
Zhang

**Comment by almutlue** [comment]
Dear Zhang,

thanks a lot for your interest. You can find the code to reproduce the ternary plots [here](https://github.com/almutlue/batch_snakemake/blob/master/src/summary/var_part_ct.Rmd). I also wrote a small variation of that script which generates some random input data for you to easily try and run the code without the intermediate file objects that are input to the script and sent it as mail.
If you are also interested in running variancePartitioning to calculate the variance attributed to different factors of your data you can find more details about the method [here](https://bioconductor.org/packages/release/bioc/html/variancePartition.html) and find my implementation [here](https://github.com/almutlue/batch_snakemake/blob/master/src/analysis/variance_part_ct.R)


Best wishes,
Almut

**Comment by zhanglab2008** [comment]
Awesome! Thanks Almut!
